inventarier/urls.py
from django.urls import path
from . import views

app_name = 'inventarier'

urlpatterns = [
	path('', views.InventarieListView.as_view(), name='list'),
	path('ny/', views.InventarieCreate.as_view(), name='create'),
	path('<inventarie_nummer>/action/', views.InventarieKommentarCreate.as_view(), name='create_kommentar'),
	path('<inventarie_nummer>/redigera/', views.InventarieUpdate.as_view(),
		name='update'), 
	path('<inventarie_nummer>/', views.InventarieDetailView.as_view(), 
		name='detail'),
]

pegasus/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
	path('inventarier/', include('inventarier.urls')),
]

inventarier/models.py
from django.db import models
from django.urls import reverse

class Produkt(models.Model):
	benämning = models.CharField(max_length=255)
	tillverkare = models.CharField(max_length=255)
	modell = models.CharField(max_length=255)

	def __str__(self):
		return "{} {} {}".format(self.benämning,
			self.tillverkare,
			self.modell
		)

	class Meta:
		verbose_name_plural = "Produkter"
	
class Inventarie(models.Model):
	inventarie_nummer = models.CharField(max_length=10,unique=True)
	serienummer = models.CharField(max_length=100)
	inköpt = models.DateField() 
	rum = models.CharField(max_length=255, default='')
	aktiv = models.BooleanField(default=True)

	produkt = models.ForeignKey('Produkt',
								on_delete=models.CASCADE,
								null=True
								)

	avdelning = models.ForeignKey('Avdelning', 
								on_delete=models.CASCADE,
								related_name='avdelning_inventarier_set',
								)
	# null=True
	utlånad_till = models.ForeignKey('Avdelning',
							on_delete=models.CASCADE,
							related_name='lånade_inventarier_set',
							null=True,
							blank=True
							)

	def get_absolute_url(self):
		return reverse("inventarier:detail",
			kwargs={"inventarie_nummer": self.inventarie_nummer}
		)  

	def __str__(self):
		return str(self.inventarie_nummer)

	class Meta:
		verbose_name_plural='Inventarier'

class InventarieKommentar(models.Model):
	skapades = models.DateTimeField(auto_now_add=True)
	ämne = models.CharField(max_length=255)
	text = models.TextField()
	inventarie = models.ForeignKey('Inventarie', on_delete=models.CASCADE)
	
	def __str__(self):
		return "{} {}".format(self.ämne, self.inventarie)

	class Meta:
		verbose_name_plural = "Inventarie kommentarer"
	def get_absolute_url(self):
		return reverse("inventarier:detail",
			kwargs={"inventarie_nummer": self.inventarie.inventarie_nummer})

class Avdelning(models.Model):
	avdelning_namn = models.CharField(max_length=255)
	kostnadsställe = models.CharField(max_length=10)
	lokal = models.CharField(max_length=255)
	
	def __str__(self):
		return self.avdelning_namn

	class Meta:
		verbose_name_plural = "Avdelningar"	

inventarier/views.py
from django.shortcuts import get_object_or_404
from django.http import HttpResponse
from django.urls import reverse_lazy
from django.views.generic import (
	ListView, DetailView, 
	CreateView, UpdateView, 
	DeleteView
)

from .models import Inventarie, InventarieKommentar


class InventarieListView(ListView):
	model = Inventarie

class InventarieDetailView(DetailView):
	model = Inventarie
	slug_url_kwarg = 'inventarie_nummer'
	slug_field = 'inventarie_nummer'

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		if self.object.aktiv == True:
			action = "Inaktivera"
		else:
			action = "Aktivera"
		context['action'] = action
		return context

class InventarieCreate(CreateView):
	model = Inventarie
	fields = ['inventarie_nummer', 'serienummer', 'rum', 'inköpt', 'produkt', 'avdelning', 'utlånad_till']

class InventarieUpdate(UpdateView):
	model = Inventarie
	fields = ['inventarie_nummer', 'serienummer', 'rum', 'inköpt', 'produkt', 'avdelning', 'utlånad_till']

	def get_object(self):
		return get_object_or_404(Inventarie, inventarie_nummer=self.kwargs['inventarie_nummer'])
	
class InventarieKommentarCreate(CreateView):
	model = InventarieKommentar
	fields = ['text', ]

#	def get_initial(self):
#		initial = super().get_initial()	
#		initial['text'] = 'hejsan'
#		inventarie = get_object_or_404(Inventarie, 
#			inventarie_nummer=self.kwargs['inventarie_nummer'])
#		initial['inventarie'] = inventarie
#		if isinstance(initial['inventarie'], Inventarie):
#			print("is correct instance")
#		return initial

	def get_context_data(self, **kwargs):
		context = super().get_context_data(**kwargs)
		inventarie = get_object_or_404(Inventarie,
			inventarie_nummer=self.kwargs['inventarie_nummer'])
		context['inventarie'] = inventarie 

		if inventarie.aktiv == True:
			action = "Inaktivera"
		else:
			action = "Aktivera"
		context['action'] = action

		return context

	def form_valid(self, form):
		inventarie_kommentar = form.instance
		inventarie_kommentar.inventarie = get_object_or_404(Inventarie,
			inventarie_nummer=self.kwargs['inventarie_nummer'])

		if inventarie_kommentar.inventarie.aktiv == True:
			inventarie_kommentar.inventarie.aktiv = False
			ämne = "Inaktivering av Inventarie"
			print("Inventarie inaktiveras")
		else:
			inventarie_kommentar.inventarie.aktiv = True
			ämne = "Aktivering av Inventarie"
			print("Inventarie aktiveras")

		inventarie_kommentar.ämne = ämne
		inventarie_kommentar.inventarie.save()	

		return super().form_valid(form)

inventarier/templates/inventarier/inventarie_detail.html
{% extends 'base_inventarier.html' %}
	{% block title %}Inventarie {{ inventarie }} spec{% endblock %}
	{% block breadcrumbs %}
		<li class="breadcrumb-item"><a href="{% url 'inventarier:list' %}">Inventarier</a></li>
		<li class="breadcrumb-item active" aria-current="page">{{ inventarie }}</li>
	{% endblock %}
	{% block content %}
		
		<h1> Inventarie Spec </h1>

		<h2> {{ inventarie }} </h2>
		<h2> {{ inventarie.produkt }} </h2>
		<h2> {{ inventarie.serienummer }} </h2>
		<h2> {{ inventarie.avdelning }} </h2>
		<h2> 
			{% if inventarie.utlånad_till %}
				Utlånad till {{ inventarie.utlånad_till }}
			{% endif %} 
		</h2>
		<h2> {{ inventarie.rum }} </h2>
		<h2> {{ inventarie.inköpt }} </h2>

		<a href="{% url 'inventarier:update' inventarie_nummer=inventarie.inventarie_nummer %}">Redigera</a>
		<a href="{% url 'inventarier:create_kommentar' inventarie_nummer=inventarie.inventarie_nummer %}">{{ action}}</a>
	{% endblock %}

inventarier/templates/inventarier/inventarie_form.html
{% extends 'base_inventarier.html' %}

{% block breadcrumbs %}
	<li class="breadcrumb-item"><a href="{% url 'inventarier:list' %}">Inventarier</a></li>
	{% if form.instance.pk %}
		<li class="breadcrumb-item"><a href="{% url 'inventarier:detail' inventarie_nummer=form.instance.inventarie_nummer %}">{{ form.instance.inventarie_nummer }}</a></li>
		<li class="breadcrumb-item active" aria-current="page">Redigera</li>
	{% else %}
		<li class="breadcrumb-item active" aria-current="page">Ny inventarie</li>
	{% endif %}
{% endblock %}

{% block content %}
	<h1>
		{% if not form.instance.pk %}
			Ny Inventarie
		{% else %}
			Redigera {{ form.instance.inventarie_nummer }}
		{% endif %}
	</h1>

	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Spara">
	</form>
{% endblock %}

inventarier/templates/inventarier/inventarie_list.html
{% extends 'base_inventarier.html' %}
	{% block title %} 
		Inventarier
	{% endblock %}

	{% block breadcrumbs %}
			<li class="breadcrumb-item active" aria-current="page">Inventarier</li>
	{% endblock %}

	{% block content %}
		<h1> Hej, Inventarie-Index </h1>

		<ul>
			{% for inventarie in inventarie_list %}
				<li>
					<a href="{% url 'inventarier:detail' inventarie_nummer=inventarie.inventarie_nummer %}">{{ inventarie }}</a>
				</li>
			{% endfor %}
		</ul>

		<a href="{% url 'inventarier:create' %}">Skapa Ny inventarie</a>
	{% endblock %}

inventarier/templates/inventarier/inventariekommentar_form.html
{% extends 'base_inventarier.html' %}
{% block breadcrumbs %}
	<li class="breadcrumb-item"><a href="{% url 'inventarier:list' %}">Inventarier</a></li>
	<li class="breadcrumb-item"><a href="{% url 'inventarier:detail' inventarie_nummer=inventarie.inventarie_nummer %}">{{ inventarie.inventarie_nummer }}</a></li>
	<li class="breadcrumb-item active" aria-current="page">{{ action }}</li>
{% endblock %}

{% block content %}
	<h1> {{ action }} {{ inventarie.inventarie_nummer }} </h1>


	<form method="POST">
		{% csrf_token %}
		{{ form.as_p }}
	<input type="submit" value="{{ action }}">
	</form>
{% endblock %}

templates/base_inventarier.html
<!doctype html>
<html>
	<head>
		<title>{% block title %}{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
	</head>

	<body>
		
		<nav aria-label="breadcrumb">
			<ol class="breadcrumb">
				{% block breadcrumbs %}
				{% endblock %}
			</ol>
		</nav>
		{% block content %}

		{% endblock %}

		<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
	</body>
</html>